### ISSUE TITLE
Add more types for Management

### ISSUE THREAD

**Issue by andrei-ivanov** [decisionrules/decisionrules-js#1]
Using version `3.0.0`, I see the `Management` API uses a lot of `object` and `any` where it could be an explicit type.

**Comment by vojtechmikes-epptec** [comment]
Could you please provide method names where you think it should be more explicitly typed?

**Comment by ghost** [comment]
Could you please provide method names where you think it should be more explicitly typed?

EDIT: Reopening (misclick)

**Comment by andrei-ivanov** [comment]
- `getRule(ruleId: string, version?: number): Promise<any>`
- `getSpaceItems(): Promise<any>`
- `createRule(rule: object): Promise<any>`
and I think all the others in `Management` that use `object` and `any`

**Comment by ghost** [comment]
Thank you for the feedback, we appreciate it.

We will take a look into more explicit types in next release.

Closing issue for now.

**Comment by andrei-ivanov** [comment]
Any ETA on this? It's been a lot of time... I think this should actually stay open until it gets implemented

**Comment by ten-petr** [comment]
Hello Andrei, 
the issue was accidentally closed by @vojtechmikes-epptec and therefore did not make it to the implementation backlog.
Anyway, I am adding the issue to the backlog and according to the current workload of the technical team, it looks like an implementation at the turn of Q3/Q4.

**Comment by tomaserben** [comment]
Hey @andrei-ivanov,

we have released a new version 3.0.4 where all the methods inside `Management` should have explicit types if possible.
It is possible that some of the actual return values will have additional properties not included in the model, however we hope that it won't be a problem.

Please try it out and let us know what you think about it.

In case you find any bug, don't hesitate to contact us.
We will try to resolve it as soon as possible.

Thanks for your patience.

**Comment by ten-petr** [comment]
JS SDK update completed.
Closing the Issue
